[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "feed-client"
version = "0.1.0"
description = ''
readme = "README.md"
requires-python = ">=3.8"
authors = []

[project.scripts]
feed-client = "feed_client.main:main"
